[package]
name = "fastembed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
flate2 = { version = "1.0" }
minreq = { version = "2.10", default-features = false, features = ["https-rustls"] }
ndarray = { version = "0.15", default-features = false }
ort = { version = "1", features = ["load-dynamic"] }
rayon = { version = "1.7", default-features = false }
tar = { version = "0.4", default-features = false }
tokenizers = { version = "0.14" }
