name: Semantic Release
on:
  push:
    branches:
      - main
      - beta
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔧 setup Bun"
        uses: oven-sh/setup-bun@v1

      - name: "📦 install dependencies"
        run: bun install

      - name: "Semantic release🚀"
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_AUTHOR_NAME: $(git log -1 --pretty=format:%an ${GITHUB_SHA})
          GIT_AUTHOR_EMAIL: $(git log -1 --pretty=format:%ae ${GITHUB_SHA})
        run: |
            bun x semantic-release
  
      - name: "echo outputs"
        run: |
          echo "RELEASE_TAG: ${{ env.RELEASE_TAG }}"
          echo "RELEASE_VERSION: ${{ env.RELEASE_VERSION }}"
          echo "outputs.release-tag: ${{ steps.release.outputs.release-tag }}"
          echo "outputs.release-version: ${{ steps.release.outputs.release-version }}"
      
